### ISSUE TITLE
map item code is not set in extensions.code

### ISSUE THREAD

**Issue by the-vampiire** [the-vampiire/apollo-error-converter#5]
looks like `toApolloError` overwrites `extensions.code` to `INTERNAL_SERVER_ERROR` instead of the `mapItem.code`. manually set `extensions.code` to use the mapItem value after conversion

**Comment by BlancoSebastianEzequiel** [comment]
According to how this apollo function its defined, if we passed code as an argument like this:
```
function createApolloError(graphQLError, mapItem) {
  const { originalError, path, locations } = graphQLError;
  const { message, data = {}, code = defaultFallback.code } = mapItem;

  return toApolloError({
    path,
    message,
    locations,
    code
    extensions: {
      code,
      data: typeof data === "function" ? data(originalError) : data,
    },
  });
}

```
this overrides our custom code with our cutom code again. This should fix this bug.

**Comment by the-vampiire** [comment]
sorry haven’t worked on this in a while. i’m not sure i understand. the code is only passed in extensions as of now. 

is your solution to pass it top level as well?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BlancoSebastianEzequiel** [comment]
Exactly. If you see the implementation for `toApolloError` is the following:
```
export function toApolloError(
  error: Error & { extensions?: Record<string, any> },
  code: string = 'INTERNAL_SERVER_ERROR',
): Error & { extensions: Record<string, any> } {
  let err = error;
  if (err.extensions) {
    err.extensions.code = code;
  } else {
    err.extensions = { code };
  }
  return err as Error & { extensions: Record<string, any> };
}
```
So, if you pass the code at top level, the function `toApolloError` won't take its default value

**Comment by the-vampiire** [comment]
there is a PR in #12 that looks to be similar to what you are proposing.

however, they propose passing it as the second argument directly rather than top level in the `error` object. this seems like it would solve this issue as well. what do you think?

**Comment by BlancoSebastianEzequiel** [comment]
yes, I think that would solve it. Now that i see it, pasing the code at top level wont solve it, but as a second argument would, so go ahead yes

**Comment by the-vampiire** [comment]
thanks @kgricour and @BlancoSebastianEzequiel for the solution. the latest v1.1.1 is now released with this change along with some vulnerability fixes.
